### ISSUE TITLE
Invalid device name on CentOS

### ISSUE THREAD

**Issue by dblessing** [chef-cookbooks/aws#134] opened 2015-04-22 15:58 UTC
```
================================================================================
    Error executing action `attach` on resource 'aws_ebs_volume[sdi1]'
    ================================================================================

    Aws::EC2::Errors::InvalidParameterValue
    ---------------------------------------
    Value (/dev/sdi1) for parameter device is invalid. /dev/sdi1 is not a valid EBS device name.

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:212:in `attach_volume'
    /var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:70:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:68:in `block in class_from_file'
```

**Comment by iennae** [comment] 2016-03-11 21:46
This is a duplicate of #148, so closing this.

**Closed by iennae** 2016-03-11 21:46 UTC
